import = [
  "~/.config/alacritty/catppuccin-frappe.toml",
]

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
{ key = "J", mods = "Alt", chars = "\\x1bj" },
{ key = "K", mods = "Alt", chars = "\\x1bk" },
]


[window]
decorations = "None"
# padding.x = 10
# padding.y = 10
# opacity = 0.7
# blur = true

[font]

normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Light"
size = 19

