import = [
  "~/.config/alacritty/alacritty-papercolor-light.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "None"

opacity = 0.7
blur = true

[font]

normal.family = "JetBrainsMono Nerd Font Mono"
size = 20

